// Code generated by protoc-gen-go.
// source: xp.proto
// DO NOT EDIT!

/*
Package xp is a generated protocol buffer package.

It is generated from these files:
	xp.proto

It has these top-level messages:
	Header
	Return
	Request
	Response
*/
package xp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Sequence    uint64   `protobuf:"varint,1,opt,name=sequence" json:"sequence,omitempty"`
	Cmd         uint32   `protobuf:"varint,2,opt,name=cmd" json:"cmd,omitempty"`
	SubCmd      uint32   `protobuf:"varint,3,opt,name=sub_cmd,json=subCmd" json:"sub_cmd,omitempty"`
	ClientId    string   `protobuf:"bytes,4,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Identity    string   `protobuf:"bytes,5,opt,name=identity" json:"identity,omitempty"`
	AccessToken string   `protobuf:"bytes,6,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Resource    string   `protobuf:"bytes,7,opt,name=resource" json:"resource,omitempty"`
	Permission  []string `protobuf:"bytes,8,rep,name=permission" json:"permission,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Header) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Header) GetSubCmd() uint32 {
	if m != nil {
		return m.SubCmd
	}
	return 0
}

func (m *Header) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Header) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Header) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Header) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Header) GetPermission() []string {
	if m != nil {
		return m.Permission
	}
	return nil
}

type Return struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Return) Reset()                    { *m = Return{} }
func (m *Return) String() string            { return proto.CompactTextString(m) }
func (*Return) ProtoMessage()               {}
func (*Return) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Return) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Return) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Request struct {
	Head *Header `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Body []byte  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetHead() *Header {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Head *Header `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Ret  *Return `protobuf:"bytes,2,opt,name=ret" json:"ret,omitempty"`
	Body []byte  `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetHead() *Header {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Response) GetRet() *Return {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*Return)(nil), "Return")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("xp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0x2f, 0x69, 0xfe, 0xdc, 0xf6, 0x93, 0x90, 0x17, 0x0c, 0x95, 0x50, 0xc8, 0x94,
	0xa9, 0x03, 0x6c, 0xac, 0x2c, 0xb0, 0x5a, 0x88, 0xb5, 0x4a, 0xec, 0x2b, 0xb0, 0x20, 0x76, 0xf0,
	0x75, 0x24, 0xfa, 0xc4, 0xbc, 0x06, 0xb2, 0xad, 0x16, 0x26, 0xb6, 0x73, 0x7f, 0x57, 0xe7, 0xd8,
	0xc7, 0x86, 0xfa, 0x73, 0xde, 0xcd, 0xce, 0x7a, 0xdb, 0x7d, 0x65, 0x50, 0x3e, 0xe0, 0xa0, 0xd0,
	0xb1, 0x4b, 0xa8, 0x09, 0x3f, 0x16, 0x34, 0x12, 0x79, 0xd6, 0x66, 0x7d, 0x21, 0x4e, 0x33, 0x3b,
	0x83, 0x5c, 0x4e, 0x8a, 0xff, 0x6b, 0xb3, 0xfe, 0xbf, 0x08, 0x92, 0x9d, 0x43, 0x45, 0xcb, 0xb8,
	0x0f, 0x34, 0x8f, 0xb4, 0xa4, 0x65, 0xbc, 0x9f, 0x14, 0xdb, 0x42, 0x23, 0xdf, 0x35, 0x1a, 0xbf,
	0xd7, 0x8a, 0x17, 0x6d, 0xd6, 0x37, 0xa2, 0x4e, 0xe0, 0x51, 0x85, 0x33, 0xb4, 0x42, 0xe3, 0xb5,
	0x3f, 0xf0, 0x55, 0xda, 0x1d, 0x67, 0x76, 0x0d, 0x9b, 0x41, 0x4a, 0x24, 0xda, 0x7b, 0xfb, 0x86,
	0x86, 0x97, 0x71, 0xbf, 0x4e, 0xec, 0x29, 0xa0, 0x60, 0x77, 0x48, 0x76, 0x71, 0x12, 0x79, 0x95,
	0xec, 0xc7, 0x99, 0x5d, 0x01, 0xcc, 0xe8, 0x26, 0x4d, 0xa4, 0xad, 0xe1, 0x75, 0x9b, 0xf7, 0x8d,
	0xf8, 0x45, 0xba, 0x1d, 0x94, 0x02, 0xfd, 0xe2, 0x0c, 0x63, 0x50, 0x48, 0xab, 0x52, 0xc9, 0x95,
	0x88, 0x3a, 0x14, 0x9c, 0xe8, 0x25, 0x16, 0x6c, 0x44, 0x90, 0xdd, 0x1d, 0x54, 0x22, 0xd4, 0x27,
	0xcf, 0xb6, 0x50, 0xbc, 0xe2, 0xa0, 0xa2, 0x61, 0x7d, 0x53, 0xed, 0xd2, 0x83, 0x89, 0x08, 0x43,
	0xda, 0x68, 0xd5, 0x21, 0x5a, 0x37, 0x22, 0xea, 0xee, 0x19, 0x6a, 0x81, 0x34, 0x5b, 0x43, 0xf8,
	0xb7, 0xf9, 0x02, 0x72, 0x87, 0x3e, 0x7a, 0xc3, 0x2e, 0x5d, 0x50, 0x04, 0x76, 0xca, 0xcd, 0x7f,
	0x72, 0xc7, 0x32, 0x7e, 0xda, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x01, 0x5f, 0xb9,
	0xc0, 0x01, 0x00, 0x00,
}
